In [1]:
import numpy as np

nodes = ['A','B','C','D']

adj_matrix = np.array([
    [0,1,1,0],
    [0,0,1,0],
    [1,0,0,0],
    [0,0,1,0]
])
print(adj_matrix)

[[0 1 1 0]
 [0 0 1 0]
 [1 0 0 0]
 [0 0 1 0]]


In [2]:
N = len(nodes)
d = 0.85
tolerance = 0.001
max_iterations = 10

PR = np.ones(N) / N

outgoing_links = np.sum(adj_matrix, axis=1)

print("Initial Page Rank:")
for i in range(N):
    print(nodes[i], PR[i])

for iteration in range(max_iterations):

    new_PR = np.ones(N) * ((1-d)/N)

    for i in range(N):
        for j in range(N):
            if adj_matrix[j,i] == 1:
                new_PR[i] = new_PR[i] + d * (PR[j] / outgoing_links[j])

    print("\nIteration", iteration + 1)

    for i in range(N):
        print(nodes[i], round(new_PR[i], 6))

    if np.max(np.abs(new_PR - PR)) < tolerance:
        PR = new_PR
        print("\nConvergence reached.")
        break

    PR = new_PR

Initial Page Rank:
A 0.25
B 0.25
C 0.25
D 0.25

Iteration 1
A 0.25
B 0.14375
C 0.56875
D 0.0375

Iteration 2
A 0.520937
B 0.14375
C 0.297812
D 0.0375

Iteration 3
A 0.290641
B 0.258898
C 0.412961
D 0.0375

Iteration 4
A 0.388517
B 0.161022
C 0.412961
D 0.0375

Iteration 5
A 0.388517
B 0.20262
C 0.371364
D 0.0375

Iteration 6
A 0.353159
B 0.20262
C 0.406721
D 0.0375

Iteration 7
A 0.383213
B 0.187593
C 0.391694
D 0.0375

Iteration 8
A 0.37044
B 0.200366
C 0.391694
D 0.0375

Iteration 9
A 0.37044
B 0.194937
C 0.397123
D 0.0375

Iteration 10
A 0.375054
B 0.194937
C 0.392509
D 0.0375


In [3]:
print("\nFinal Page Rank:")
for i in range(N):
    print(nodes[i], round(PR[i], 6))


Final Page Rank:
A 0.375054
B 0.194937
C 0.392509
D 0.0375
